# Generated by Django 3.2.6 on 2021-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
