# Generated by Django 3.2.6 on 2021-09-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_registradas',
            fields=[
                ('id_cliente', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('id_nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('id_debe', models.BooleanField(default=False)),
                ('id_total', models.FloatField(null=True, verbose_name='total')),
                ('fecha', models.DateField(auto_now=True, verbose_name='última visita')),
                ('id_celular', models.IntegerField(unique=True, verbose_name='celular')),
            ],
        ),
        migrations.CreateModel(
            name='resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(verbose_name='saldo')),
                ('entrega', models.FloatField(verbose_name='entrega')),
                ('venta', models.FloatField(verbose_name='venta')),
                ('producto', models.CharField(max_length=150, verbose_name='producto')),
                ('fecha', models.DateField(verbose_name='última visita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas_registradas')),
            ],
        ),
    ]
