# Generated by Django 3.2.6 on 2021-09-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_registradas',
            old_name='id_celular',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='cuentas_registradas',
            old_name='id_debe',
            new_name='debe',
        ),
        migrations.RenameField(
            model_name='cuentas_registradas',
            old_name='id_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cuentas_registradas',
            old_name='id_total',
            new_name='total',
        ),
    ]
