# Generated by Django 3.2.6 on 2021-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20210918_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='id_cliente',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
