# Generated by Django 3.2.6 on 2021-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20210920_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='celular',
            field=models.BigIntegerField(unique=True, verbose_name='celular'),
        ),
    ]
