# Generated by Django 3.2.6 on 2021-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuentas_registradas_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
