# Generated by Django 3.2.6 on 2021-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuentas_registradas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='total',
            field=models.FloatField(null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='debe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='entrega',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='producto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='venta',
            field=models.FloatField(default=0, verbose_name='venta'),
        ),
    ]
