# Generated by Django 3.2.6 on 2021-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_cuentas_registradas_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='saldo',
            field=models.FloatField(blank=True, null=True, verbose_name='saldo'),
        ),
    ]
