# Generated by Django 3.2.6 on 2021-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_alter_resumen_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='total',
        ),
        migrations.AlterField(
            model_name='resumen',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
