# Generated by Django 3.2.6 on 2021-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_auto_20210922_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='saldo',
        ),
        migrations.AddField(
            model_name='cuentas_registradas',
            name='saldo',
            field=models.FloatField(blank=True, null=True, verbose_name='saldo'),
        ),
    ]
