# Generated by Django 3.2.6 on 2021-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_auto_20210922_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas_registradas',
            name='saldo',
        ),
        migrations.AddField(
            model_name='resumen',
            name='saldo',
            field=models.FloatField(blank=True, null=True, verbose_name='saldo'),
        ),
        migrations.AddField(
            model_name='resumen',
            name='total',
            field=models.FloatField(default=0, null=True, verbose_name='total'),
        ),
    ]
