# Generated by Django 3.2.6 on 2021-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_alter_resumen_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='celular',
            field=models.BigIntegerField(unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='debe',
            field=models.BooleanField(default=False, verbose_name='Tiene Saldo/ No tiene'),
        ),
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre Cliente'),
        ),
    ]
