# Generated by Django 3.2.6 on 2021-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_auto_20210923_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_registradas',
            name='celular',
            field=models.CharField(max_length=10, unique=True, verbose_name='Celular'),
        ),
    ]
